steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone','https://source.developers.google.com/p/${_PROJECT}/r/${_REPO_NAME}']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build',' -t','gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}','.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}']

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/${_DEPLOYMENTNAME}'
      - ${_DEPLOYMENTNAME}=gcr.io/${_PROJECT}/${_CONTAINERNAME}:${VERSION}'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
    
    
    substitutions:
         _PROJECT : rb-munish_playground
         _ZONE : us-central1
         _GKE_CLUSTER: publicclut

         _DEPLOYMENTNAME: deployment-file
         _CONTAINERNAME : flaskcode
         _REPO_NAME: github_aroramanan366_cicd

         _VERSION: v1.0
